# Application
spring.application.name=grading-service
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/grading_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true