# Application
spring.application.name=etudiant-service
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/etudiants_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis Cache
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.instance.prefer-ip-address=true

# Swagger
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true