# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://db:5432/etudiants_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Port du serveur
server.port=8080